stages:
  - Testing
  - Deploy

default:
  image: ctr.cobalt.rocks/cobalt/nix-container-builder/niks3-cached:latest
  tags:
    - nix
    - x86_64-linux
    - nixos

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/

Lint:
  stage: Testing
  allow_failure: true
  script:
    - nix develop -c npm ci --no-audit --no-fund
    - nix develop -c pre-commit run --all-files

.template: &rs-deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    # Add ssh folder
    - mkdir -p ~/.ssh
    # Dump keys from CI variables to files
    - echo "$KEY" > ~/.ssh/id
    - echo "$CD_DIST_HOST_BORON" >> ~/.ssh/known_hosts
    # SSH agent requires specific permissions
    - chmod 644 ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id
  script:
    - nix build -L .#$PACKAGE
    - nix develop .#ci -c rsync -e "ssh -p $CD_DIST_PORT -i ~/.ssh/id" -Przv --checksum --info=progress2 --delete ./result/ "coderdojo-$PACKAGE@$CD_DIST_HOST:."

# CD:Red:exp:
#   <<: *rs-deploy
#   stage: Deploy
#   environment:
#     name: production-1b
#     url: https://coderdojo.red
#   variables:
#     PACKAGE: red
#     CD_HOST_KEY: "$CD_DIST_HOST_BORON"
#     CD_DIST_PORT: 2077
#     CD_DIST_HOST: boron.arasaka.io
#     CD_DIST_USER: coderdojo-red
#     KEY: "$CD_RED_PRIVATE_KEY"

# CD:Blue:exp:
#   <<: *rs-deploy
#   stage: Deploy
#   environment:
#     name: production-2b
#     url: https://coderdojo.blue
#   variables:
#     PACKAGE: blue
#     CD_HOST_KEY: "$CD_DIST_HOST_BORON"
#     CD_DIST_PORT: 2077
#     CD_DIST_HOST: boron.arasaka.io
#     CD_DIST_USER: coderdojo-blue
#     KEY: "$CD_BLUE_PRIVATE_KEY"

CD:Red:
  <<: *rs-deploy
  stage: Deploy
  environment:
    name: production-1
    url: https://coderdojo.red
  variables:
    PACKAGE: red
    KEY: "$CD_RED_PRIVATE_KEY"
    CD_DIST_PORT: 2077
    CD_DIST_HOST: boron.arasaka.io

CD:Blue:
  <<: *rs-deploy
  stage: Deploy
  environment:
    name: production-2
    url: https://coderdojo.blue
  variables:
    PACKAGE: blue
    KEY: "$CD_BLUE_PRIVATE_KEY"
    CD_DIST_PORT: 2077
    CD_DIST_HOST: boron.arasaka.io
