image: ghcr.io/nix-community/docker-nixpkgs/nix-flakes

stages:
  - Testing
  - Deploy

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/

Lint:
  stage: Testing
  tags:
    - nix
  script:
    - nix develop -c pre-commit run

.template: &rs-deploy # NOTE: helium is the only runner allowed to access the coderdojo ssh repos
  tags:
    - nix
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    # Add shh folder
    - mkdir -p ~/.ssh
    # Dump keys from CI variables to files
    - echo "$KEY" > ~/.ssh/id_rsa
    - echo "$CD_HOST_KEY" >> ~/.ssh/known_hosts
    # SSH agent requires specific permissions
    - chmod 644 ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
  script:
    - nix build ".#$PACKAGE"
    - nix develop .#ci -c rsync -e "ssh -p $CD_DIST_PORT -i ~/.ssh/id_rsa" -PL -rzuc --info=progress2 --delete ./result/  "$CD_DIST_USER@$CD_DIST_HOST:"

CD:Red:exp:
  <<: *rs-deploy
  stage: Deploy
  environment:
    name: production-1b
    url: https://coderdojo.red
  variables:
    PACKAGE: red
    CD_HOST_KEY: "$CD_DIST_HOST_BORON"
    CD_DIST_PORT: 2077
    CD_DIST_HOST: boron.arasaka.io
    CD_DIST_USER: coderdojo-red
    KEY: "$CD_RED_PRIVATE_KEY"

CD:Blue:exp:
  <<: *rs-deploy
  stage: Deploy
  environment:
    name: production-2b
    url: https://coderdojo.blue
  variables:
    PACKAGE: blue
    CD_HOST_KEY: "$CD_DIST_HOST_BORON"
    CD_DIST_PORT: 2077
    CD_DIST_HOST: boron.arasaka.io
    CD_DIST_USER: coderdojo-blue
    KEY: "$CD_BLUE_PRIVATE_KEY"

CD:Red:
  <<: *rs-deploy
  stage: Deploy
  environment:
    name: production-1
    url: https://coderdojo.red
  variables:
    PACKAGE: red
    KEY: "$CD_RED_PRIVATE_KEY"

CD:Blue:
  <<: *rs-deploy
  stage: Deploy
  environment:
    name: production-2
    url: https://coderdojo.blue
  variables:
    PACKAGE: blue
    KEY: "$CD_BLUE_PRIVATE_KEY"
