
# chapters
[[chapters]]
name = "Euler-Gruppe"
path = "@/euler/_index.md"
color = "#66CCFF"
icon = "reception-1"

[[chapters]]
name = "7. Kyū"
path = "@/kyo-7/_index.md"
color = "#FFFFFF"
icon = "reception-2"

[[chapters]]
name = "6. Kyū"
path = "@/kyo-6/_index.md"
color = "#FFFF00"
icon = "reception-3"

[[chapters]]
name = "5. Kyū"
path = "@/kyo-5/_index.md"
color = "#FF9900"
icon = "reception-4"

[[chapters]]
name = "4. Kyū"
path = "@/kyo-4/_index.md"
color = "#33CC33"
icon = "reception-5"

[[chapters]]
name = "3. Kyū"
path = "@/kyo-3/_index.md"
color = "#0066FF"
icon = "reception-6"

[[chapters]]
name = "2. Kyū"
path = "@/kyo-2/_index.md"
color = "#6600FF"
icon = "reception-7"

[[chapters]]
name = "1. Kyū"
path = "@/kyo-1/_index.md"
color = "#663300"
icon = "reception-8"

[[chapters]]
name = "1. Dan"
path = "@/dan-1/_index.md"
color = "#000000"
icon = "reception-9"


