# The URL the site will be built for
# WARNING: Will be overwritten in CD-builds
base_url = "DOMAIN"

# Whether to automatically compile all Sass files in the sass directory
# Will be compressed & prefixed for production builds
compile_sass = true

# Minify
# Breaks syntax highlighting sometimes - has been replaced for production builds with compress.ts
minify_html = false

# feeds
generate_feed = false

# Whether to build a search index to be used later on by a JavaScript library
# You may want this buuuuuuut I don't want to take care of it right now. Might be done later
build_search_index = false

[markdown]
# Whether to do syntax highlighting
highlight_code = true    # Adjust to your liking
highlight_theme = "nord"

[extra]
# Enable katex for webpage
katex = false             # Display "Copy Link" Button
link = true               # Ehhhm Donno
sctionlisting = true      # Adjust settings for sitemap generation (to hide sites from google/ bing …)
list = true
priority = 0.5            # Whether to display footer
footer = true             # Used for footer and copyright
base_domain = "localhost" # WARNING: Will be overwritten in CD-builds


brand_alt = "Coderdojo Red and Blue Logo" # Used for brand icon (navbar top left)
brand_src = "images/brand.svg"            # Used for brand icon (navbar top left)
