
# chapters
[[chapters]]
name = "Euler-Gruppe"
path = "@/euler/_index.md"
color = "#b48ead"
icon = "journal-code"

[[chapters]]
name = "Überblick Dojo"
path = "@/kyo-info/_index.md"
color = "#55CCFF"
icon = "reception-4"

[[chapters]]
name = "7. Kyū"
path = "@/kyo-7/_index.md"
color = "#fff"
icon = "reception-1"

[[chapters]]
name = "6. Kyū"
path = "@/kyo-6/_index.md"
color = "#FFFF00"
icon = "reception-1"

[[chapters]]
name = "5. Kyū"
path = "@/kyo-5/_index.md"
color = "#FF9900"
icon = "reception-2"

[[chapters]]
name = "4. Kyū"
path = "@/kyo-4/_index.md"
color = "#33cc33"
icon = "reception-2"

[[chapters]]
name = "3. Kyū"
path = "@/kyo-3/_index.md"
color = "#0066ff"
icon = "reception-3"

[[chapters]]
name = "2. Kyū"
path = "@/kyo-2/_index.md"
color = "#35077a"
icon = "reception-3"

[[chapters]]
name = "1. Kyū"
path = "@/kyo-1/_index.md"
color = "#733111"
icon = "reception-4"

[[chapters]]
name = "1. Dan"
path = "@/dan-1/_index.md"
color = "#001"
icon = "reception-4"

[[chapters]]
name = "2. Dan"
path = "@/dan-2/_index.md"
color = "#000000"
icon = "reception-4"

[[chapters]]
name = "Mentoren"
path = "@/kyo-info/mentoren.md"
color = "#fff"
icon = "reception-4"
